# ModelConfig
model_config:
  context_size: 100
  n_embed: 90
  n_layer: 3
  n_head: 3
  use_bias: false
  dropout_rate: 0
batch_size: 15
train_steps: 500
lr: 0.0003
warmup_iters: 50
min_lr: 3.0e-05
gradient_accumulation_steps: 16
lr_decay_iters: 500
est_interval: 100
est_steps: 20
