batch_size: 50
beta1: 0.9
beta2: 0.95
decay_lr: true
est_interval: 500
est_steps: 200
gradient_accumulation_steps: 16
lr: 0.0009
lr_decay_iters: 700000
min_lr: 9.0e-05
model_config:
  add_ln_before_decoder_ff: false
  add_pos_embed_to_decoder: false
  context_size: 200
  cross_attn_config:
    n_head: 10
    use_bias: false
  detach_type: null
  dropout_rate: 0
  embedding_ln_type: null
  embedding_loss_coeff: null
  embedding_loss_type: 1
  n_embed: 150
  n_head: 5
  n_layer: 13
  order_type: 1
  sub_pos_embed_to_decoder: 2
  use_bias: false
  use_ln_on_encoder_out: null
train_steps: 9000
warmup_iters: 300
weight_decay: 0.1
