program: deep_sight_transformer/training_script.py
name: wikipedia_no_loss
project: future_encoder_transformer
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                value: 400
            n_embed: 
                value: 150
            n_layer: 
                value: 13
            n_head: 
                value: 5
            dropout_rate:
                value: 0
            cross_attn_config:
                parameters:
                    n_head:
                        value: 10
                    use_bias:
                        value: False
            future_context_size:
                value: null
            present_future_context_aggregation_type:
                value: null
            future_context_loss_type:
                value: 1
            future_context_loss_coeff:
                value: null
            future_context_ln_type:
                value: null
            future_context_aggregation_type:
                value: null
    batch_size: 
        value: 50
    train_steps: 
        value: 9000
    lr: 
        value: 9e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 9e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 700000
    est_interval: 
        value: 500
    est_steps: 
        value: 200