repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        stages: [push]
    -   id: isort
        name: isort --profile black
        entry: isort
        language: python
        types: [python]
        stages: [push]
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        stages: [push]
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        stages: [push]