program: transformer_dropout/training_script.py
name: harry_potter_full_new_config
project: transformer_dropout_5_encoder_decoder
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                values: [True,False]
            context_size:
                value: 100
            n_embed: 
                value: 150
            n_layer: 
                value: 12
            n_head: 
                values: [10, 15]
            dropout_rate:
                values: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
            use_learned_dropout:
                value: False
    batch_size: 
        value: 50
    train_steps: 
        value: 10000
    lr: 
        value: 3e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 3e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: # code needs to be modified 
        value: 700000
    est_interval: 
        value: 500
    est_steps:
        value: 200