program: transformer_embed.training_script.py
name: harry_potter_embed_new
project: transformer_embed_2
run_cap: 200
method: random
metric:
  goal: minimize
  name: est_val_accuracy
parameters:
    model_config:
        parameters:
            context_size:
                value: 1024
            n_embed: 
                value: 400
            n_layer: 
                value: 4
            n_head: 
                value: 4
            use_new_output_layer:
                value: True
            use_final_ln_layer:
                values: [True, False]
            dropout_rate:
                values: [0, 0.1, 0.2]     
            new_output_layer_config:
                parameters:
                    subtract_out_pos_embed:
                        values: [True, False]
                    use_cross_entropy_loss:
                        values: [True, False]

    batch_size: 
        value: 13
    train_steps: 
        value: 6000
    lr: 
        values: [6e-1, 6e-2, 6e-3,6e-4, 6e-5]
    warmup_iters: 
        value: 600
    min_lr: 
        values: [6e-2, 6e-3, 6e-4,6e-5, 6e-6]
    gradient_accumulation_steps: 
        value: 8
    lr_decay_iters: 
        value: 6000
    est_interval: 
        value: 100
    est_steps: 
        value: 100
        
    
