program: attention_dropout_transformer/training_script.py
name: final_wikipedia_config_embed_input_final_comparison_huuuge
project: ultimate_attention_dropout_transformer_new_embed
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                value: 500
            n_embed: 
                value: 300
            n_layer: 
                value: 26
            n_head: 
                value: 10
            dropout_rate:
                value: 0
            use_dropout_entropy_penalty:
                value: False
            use_dropout_l1_norm_penalty:
                value: True
            l1_norm_penalty_type:
                value: 2
            dropout_l1_norm_coeff_config:
                parameters:
                    max_coeff:
                        value: 0.1
            learned_dropout_config:
                parameters:
                    use_bias:
                        value: False
                    n_head:
                        value: 10
                    mask_rounding_type:
                        value: 3
                    shift_init:
                        value: 0
                    use_detached_input:
                        value: True
                    dropout_input_type:
                        value: 2
    batch_size: 
        value: 50
    train_steps: 
        value: 28000
    lr: 
        value: 9e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 9e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 700000
    est_interval: 
        value: 500
    est_steps: 
        value: 200