# ModelConfig
CONTEXT_SIZE = 200
N_EMBED = 200
N_LAYER = 4
N_HEAD = 4
USE_BIAS = False
DROPOUT_RATE = 0

# Training config
BATCH_SIZE = 15
TRAIN_STEPS = 500
LR = 3e-3
WARMUP_ITERS = 50
MIN_LR = 3e-4
GRADIENT_ACCUMULATION_STEPS = 16
LR_DECAY_ITERS = 500

# Estimation config
EST_INTERVAL = 50
EST_STEPS = 50
