# ModelConfig
CONTEXT_SIZE = 80
N_EMBED = 100
N_LAYER = 3
N_HEAD = 2
BIAS = False
USE_DROPOUT_ENTROPY_IN_LOSS = False
USE_DROPOUT_L1_NORM_IN_LOSS = False
USE_LEARNED_DROPOUT = False
DROPOUT_RATE = 0.0

# Training config
BATCH_SIZE = 10
TRAIN_STEPS = 1000
LR = 3e-4
WARMUP_ITERS = 50
MIN_LR = 6e-5
GRADIENT_ACCUMULATION_STEPS = 16
LR_DECAY_ITERS = 600000

# Estimation config
EST_INTERVAL = 200
EST_STEPS = 100
