program: parallel_future_transformer/training_script.py
name: wikipedia_config
project: parallel_future_transformer
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 150
            n_layer: 
                value: 13
            n_head: 
                value: 5
            dropout_rate:
                value: 0
            cross_attn_config:
                parameters:
                    n_head:
                        value: 5
                    use_bias:
                        value: False
            future_loss_type:
                values: [2,3,4]
            future_embed_type:
                values: [1,2]
            future_loss_coeff:
                value: 1
            future_embed_ln_type:
                values: [1,2,3]
    batch_size: 
        value: 50
    train_steps: 
        value: 9000
    lr: 
        value: 9e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 9e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 700000
    est_interval: 
        value: 500
    est_steps: 
        value: 200