program: transformer_dropout/training_script.py
name: harry_potter_full_dropout_baseline_repro
project: transformer_dropout_5
method: grid
run_cap: 8
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 200
            n_layer: 
                value: 4
            n_head: 
                value: 4
            dropout_rate:
                values: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
            use_learned_dropout:
                value: True
            learned_dropout_config:
                parameters:
                    use_dropout_entropy_in_loss:
                        value: True
                    use_dropout_l1_norm_in_loss:
                        value: False
                    use_sigmoid_on_dropout_mask:
                        values: [True, False]
                    use_canonical_entropy:
                        values: [True, False]
                    use_detached_x_in_dropout_mask:
                        values: [True, False]
                    A_param_config:
                        parameters:
                            init_mean:
                                values: [0, 10, 100]
                            init_std:
                                values: [0, 1, 10]
                            optimizer_type:
                                values: ["ADAMW", "SGD"]
                            lr:
                                values: [3e-2, 1, null]
                    B_param_config:
                        parameters:
                            init_mean:
                                values: [0, 3.1415, 1.5707, 1.3033]
                            init_std:
                                values: [0, 0.02]
                            optimizer_type:
                                values: ["ADAMW", "SGD"]
                            lr:
                                values: [3e-2, null]
                    dropout_entropy_lambda:
                        parameters:
                            max_lambda:
                              values: [1,2]
    batch_size: 
        value: 50
    train_steps: 
        value: 3500
    lr: 
        value: 3e-4
    warmup_iters:
        value: 100
    min_lr: 
        value: 0
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 3500
    est_interval: 
        value: 200
    est_steps: 
        value: 20