program: transformer_dropout.training_script.py
name: harry_potter_dropout_baseline
project: transfomer_dropout_3
method: grid
run_cap: 31
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            context_size:
                value: 1024
            n_embed: 
                value: 400
            n_layer: 
                value: 4
            n_head: 
                value: 4
            use_learned_dropout:
                value: False
            dropout_rate:
                values: [0, 0.1, 0.2, 0.3, 0.4]
            bias:
                values: [True, False]
            use_flash:
                value: True
    batch_size: 
        value: 15
    train_steps: 
        value: 6000
    lr: 
        values: [6e-4, 6e-3, 6e-5]
    warmup_iters: 
        value: 600
    min_lr: 
        values: [6e-5, 6e-4, 6e-6]
    gradient_accumulation_steps: 
        value: 8
    lr_decay_iters: 
        value: 6000
    est_interval: 
        value: 100
    est_steps: 
        value: 100
        
    
