program: transformer_dropout/training_script.py
name: harry_potter_full_dropout_baseline_repro
project: transformer_dropout_5
method: grid
run_cap: 8
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 200
            n_layer: 
                value: 4
            n_head: 
                value: 4
            use_learned_dropout:
                value: False
            dropout_rate:
                values: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
    batch_size: 
        value: 50
    train_steps: 
        value: 3500
    lr: 
        value: 3e-4
    warmup_iters:
        value: 100
    min_lr: 
        value: 0
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 3500
    est_interval: 
        value: 200
    est_steps: 
        value: 20