program: transformer_dropout/training_script.py
name: openweb_dropout_baseline_repro_final
project: transformer_dropout_5
method: random
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                value: True
            context_size:
                value: 1024
            n_embed: 
                value: 768
            n_layer: 
                value: 12
            n_head: 
                value: 12
            dropout_rate:
                value: 0
            use_learned_dropout:
                value: False
    batch_size: 
        value: 15 # to match the transformer_embed baseline
    train_steps: 
        value: 22000
    lr: 
        value: 6e-4
    warmup_iters:
        value: 100
    min_lr: 
        value: 6e-5
    gradient_accumulation_steps: 
        value: 40
    lr_decay_iters: 
        value: 22000
    est_interval: 
        value: 500
    est_steps: 
        value: 200