program: transformer_dropout/training_script.py
name: transformer_dropout
project: local_test
method: random
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            context_size:
                value: 50
            n_embed: 
                value: 100
            n_layer: 
                value: 3
            n_head: 
                value: 2
            use_learned_dropout:
                value: False
            dropout_rate:
                values: [0.1,0.2,0.3]
    batch_size: 
        value: 10
    train_steps: 
        value: 500
    lr: 
        value: 3e-4
    warmup_iters: 
        value: 50
    min_lr: 
        value: 6e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 500
    est_interval: 
        value: 100
    est_steps: 
        value: 20
        
    
