program: baseline_transformer/training_script.py
name: wikipedia_baseline
project: baseline_transformer
method: grid
metric:
  goal: minimize
  name: est_val_loss
early_terminate:
    type: hyperband
    min_iter: 14
    eta: 2
    strict: False
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                values: 200
            n_embed: 
                values: 200
            n_layer: 
                value: 10
            n_head: 
                value: 10
            dropout_rate:
                value: 0
    batch_size: 
        value: 50
    train_steps: 
        value: 3000
    lr: 
        value: 3e-4
    warmup_iters:
        value: 100
    min_lr: 
        value: 3e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 3000
    est_interval: 
        value: 200
    est_steps: 
        value: 100