program: encoder_decoder_transformer/training_script.py
name: wikipedia_ln_before_ffd
project: encoder_decoder_transformer
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 200
            n_layer: 
                value: 10
            n_head: 
                value: 10
            dropout_rate:
                values: [0, 0.1, 0.2, 0.3]
    batch_size: 
        value: 50
    train_steps: 
        value: 9000
    lr: 
        value: 9e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 9e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 700000
    est_interval: 
        value: 500
    est_steps: 
        value: 200