program: transformer_dropout/training_script.py
name: harry_potter_full_dropout_new_repro_no_penalty_underparametrized
project: transformer_dropout_5_attn_cosine
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 200
            n_layer: 
                value: 2
            n_head: 
                value: 2
            dropout_rate:
                value: 0.3
            use_learned_dropout:
                value: True
            learned_dropout_config:
                parameters:
                    start_layer:
                        value: 2
                    use_dropout_entropy_in_loss:
                        value: False
                    use_dropout_l1_norm_in_loss:
                        value: False
                    use_bias:
                        value: False
                    softmax_dim:
                        value: 2
                    rounding_type: # this is ignored
                        value: null
                    shift_init: # this is ignored
                        value: 1.57079632
                    n_heads:
                        values: [1, 2, 5, 10, 20, 50, 100]
                    use_canonical_entropy:
                        value: False
                    use_detached_x_in_dropout_mask:
                        value: False
                    profile_dropout_mask:
                        value: False
    batch_size: 
        value: 50
    train_steps: 
        value: 4500
    lr: 
        value: 3e-4
    warmup_iters:
        value: 200
    min_lr: 
        value: 3e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 4500
    est_interval: 
        value: 500
    est_steps:
        value: 200