program: transformer_dropout/training_script.py
name: harry_potter_full_dropout_new_repro_sub_1_d
project: transformer_dropout_5_attn
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 200
            n_layer: 
                value: 4
            n_head: 
                value: 4
            dropout_rate:
                value: 0.3
            use_learned_dropout:
                value: True
            learned_dropout_layers:
                values: [4, 3]
            learned_dropout_config:
                parameters:
                    use_dropout_entropy_in_loss:
                        value: True
                    use_dropout_l1_norm_in_loss:
                        value: False
                    use_bias:
                        value: False
                    l1_norm_pos:
                        values: [1,2]
                    n_heads:
                        value: 1
                    use_detached_x_in_dropout_mask:
                        values: [True, False]
                    dropout_entropy_lambda:
                        parameters:
                            max_lambda:
                              values: [0.5, 1, 0.1, 0.05, 0.01, 0.005]
                            coefficient:
                              values: [0.003, 0.001, 0.0006, null]
    batch_size: 
        value: 50
    train_steps: 
        value: 3000
    lr: 
        value: 3e-4
    warmup_iters:
        value: 100
    min_lr: 
        value: 3e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 3000
    est_interval: 
        value: 200
    est_steps: 
        value: 100