program: future_attention_transformer/training_script.py
name: wikipedia_config_smaller_pt3_cosine
project: future_attention_transformer_v1
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 144
            n_layer: 
                value: 28
            n_head: 
                value: 9
            dropout_rate:
                value: 0
            start_layer:
                value: 1
            end_layer:
                value: 28
            future_attn_loss_type:
                value: 1
            use_future_attn_loss:
                value: True
            future_dim:
                value: 50
            detach_future_ground_truth:
                value: True
            future_attn_loss_coeff:
                value: 1
    batch_size: 
        value: 50
    train_steps: 
        value: 9000
    lr: 
        value: 9e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 9e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 700000
    est_interval: 
        value: 500
    est_steps: 
        value: 200