# ModelConfig
CONTEXT_SIZE = 1024
N_EMBED = 600
N_LAYER = 6
N_HEAD = 6
BIAS = False
USE_DROPOUT_ENTROPY_IN_LOSS = True
USE_DROPOUT_L1_NORM_IN_LOSS = True
USE_LEARNED_DROPOUT = True
DROPOUT_ENTROPY_LAMBDA = {"min_lambda": 0, "max_lambda": 3, "coefficient": 0.007}
DROPOUT_L1_NORM_LAMBDA = {"min_lambda": 0, "max_lambda": 3, "coefficient": 0.007}

# Training config
BATCH_SIZE = 10
TRAIN_STEPS = 20000
LR = 6e-4
WARMUP_ITERS = 1000
MIN_LR = 6e-5
GRADIENT_ACCUMULATION_STEPS = 4 * 8
LR_DECAY_ITERS = 20000

# Estimation config
EST_INTERVAL = 500
EST_STEPS = 100
