# ModelConfig
CONTEXT_SIZE = 1024
N_EMBED = 600
N_LAYER = 6
N_HEAD = 6
BIAS = False
USE_DROPOUT_ENTROPY_IN_LOSS = False
USE_DROPOUT_L1_NORM_IN_LOSS = False
USE_LEARNED_DROPOUT = False
DROPOUT_RATE = 0.1

# Training config
BATCH_SIZE = 10
TRAIN_STEPS = 20000
LR = 6e-4
WARMUP_ITERS = 1000
MIN_LR = 6e-5
GRADIENT_ACCUMULATION_STEPS = 4 * 8
LR_DECAY_ITERS = 20000

# Estimation config
EST_INTERVAL = 500
EST_STEPS = 100
