wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.1
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707688701.463899
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.10.1
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
