program: transformer_dropout/training_script.py
name: openweb_baseline_yolo
project: transformer_dropout_5_head_sub
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            bias:
                value: True
            context_size:
                value: 1024
            n_embed: 
                value: 768
            n_layer: 
                value: 12
            n_head: 
                value: 12
            dropout_rate:
                value: 0
            use_learned_dropout:
                value: True
            learned_dropout_config:
                parameters:
                    use_bias:
                        value: True
                    start_layer:
                        value: 1
                    end_layer:
                        value: 12
                    normalize_by_context_size:
                        values: [True, False]
                    return_type:
                        value: 5
                    use_res_add:
                        value: True
                    softmax_dim:
                        value: 2
                    n_heads:
                        value: 12
                    profile_dropout_mask:
                        value: False
    batch_size: 
        value: 15
    train_steps: 
        value: 25000
    lr: 
        value: 6e-4
    warmup_iters:
        value: 500
    min_lr: 
        value: 6e-5
    gradient_accumulation_steps: 
        value: 40
    lr_decay_iters: # code needs to be modified 
        value: 600000
    est_interval: 
        value: 500
    est_steps:
        value: 200