wandb_version: 1

context_size:
  desc: null
  value: 100
n_embed:
  desc: null
  value: 100
n_layer:
  desc: null
  value: 3
n_head:
  desc: null
  value: 2
bias:
  desc: null
  value: false
batch_size:
  desc: null
  value: 50
training_steps:
  desc: null
  value: 1000
lr:
  desc: null
  value: 0.0003
est_interval:
  desc: null
  value: 200
est_steps:
  desc: null
  value: 100
alphabet_size:
  desc: null
  value: 91
_wandb:
  desc: null
  value:
    python_version: 3.10.1
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707691098.474043
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.1
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
