# ModelConfig
CONTEXT_SIZE = 100
N_EMBED = 90
N_LAYER = 3
N_HEAD = 3
USE_BIAS = False
DROPOUT_RATE = 0
ADD_POS_EMBED = False
ORDER_TYPE = 1
SUB_POS_EMBED = 1
ADD_LN_BEFORE_DECODER_FF = True
ENCODER_EMBED_LOSS_TYPE = 2
USE_LN_ON_ENCODER_OUT = True
ENCODER_EMBED_DETACH_TYPE = 1
ENCODER_EMBED_LN_TYPE = 1
CROSS_ATTN_CONFIG = {"use_bias": False, "n_head": 3}

# Training config
BATCH_SIZE = 15  # 50 when run on 1x A10
TRAIN_STEPS = 500
LR = 3e-4
WARMUP_ITERS = 50
MIN_LR = 3e-5
GRADIENT_ACCUMULATION_STEPS = 16
LR_DECAY_ITERS = 500

# Estimation config
EST_INTERVAL = 100
EST_STEPS = 20
