program: future_attention_transformer/training_script.py
name: wikipedia_config_no_loss
project: new_future_attention_transformer
method: grid
metric:
  goal: minimize
  name: est_val_loss
parameters:
    model_config:
        parameters:
            use_bias:
                value: False
            context_size:
                value: 200
            n_embed: 
                value: 150
            n_layer: 
                value: 26
            n_head: 
                value: 10
            dropout_rate:
                value: 0
            future_dim:
                values: [50,100,199]
            future_x_loss_type:
                value: 1
            use_future_x_loss:
                value: False
            use_ln_on_up_future:
                values: [True, False]
            detach_future_x:
                value: null
            future_x_loss_coeff:
                value: 1
    batch_size: 
        value: 50
    train_steps: 
        value: 9000
    lr: 
        value: 9e-4
    warmup_iters:
        value: 300
    min_lr: 
        value: 9e-5
    gradient_accumulation_steps: 
        value: 16
    lr_decay_iters: 
        value: 700000
    est_interval: 
        value: 500
    est_steps: 
        value: 200